// Generated by gencpp from file beginner_tutorials/wordCount.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_WORDCOUNT_H
#define BEGINNER_TUTORIALS_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/wordCountRequest.h>
#include <beginner_tutorials/wordCountResponse.h>


namespace beginner_tutorials
{

struct wordCount
{

typedef wordCountRequest Request;
typedef wordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wordCount
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::wordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::beginner_tutorials::wordCount&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::wordCount > {
  static const char* value()
  {
    return "beginner_tutorials/wordCount";
  }

  static const char* value(const ::beginner_tutorials::wordCount&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::wordCountRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::wordCount > 
template<>
struct MD5Sum< ::beginner_tutorials::wordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::wordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::wordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::wordCountRequest> should match 
// service_traits::DataType< ::beginner_tutorials::wordCount > 
template<>
struct DataType< ::beginner_tutorials::wordCountRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::wordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::wordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::wordCountResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::wordCount > 
template<>
struct MD5Sum< ::beginner_tutorials::wordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::wordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::wordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::wordCountResponse> should match 
// service_traits::DataType< ::beginner_tutorials::wordCount > 
template<>
struct DataType< ::beginner_tutorials::wordCountResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::wordCount >::value();
  }
  static const char* value(const ::beginner_tutorials::wordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_WORDCOUNT_H
